# Header
menu:
  主页: /
  归档: /archives
  标签: /tags
  分类: /categories
#  Rss: /atom.xml
#  Sitemap: /sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
